# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [5]:
import numpy as np
# formula = weight / (height**2) * 730
# height = [69, 70, 71, 72, 73, 74, 75]
# weight = [110, 120, 130, 140, 150, 160, 170]

height = np.array([69, 70, 71, 72, 73, 74, 75])
weight = np.array([110, 120, 130, 140, 150, 160, 170])

bmi = weight / (height ** 2) * 703

print(bmi)



[16.24238605 17.21632653 18.12933942 18.98533951 19.78795271 20.54054054
 21.24622222]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [10]:
def new_matrix(n_rows, n_cols):
    return np.random.rand(n_rows, n_cols)

matrix = new_matrix(5, 5)
print(matrix)


[[0.76769244 0.03275305 0.84503331 0.33577375 0.92650187]
 [0.64223304 0.85020144 0.28284439 0.63512786 0.05409689]
 [0.33524069 0.81841569 0.38072373 0.68535801 0.53881594]
 [0.43055295 0.83695434 0.39301968 0.85935312 0.40259044]
 [0.54421649 0.91725023 0.63110182 0.55647579 0.84535038]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [13]:
import csv
import numpy as np




In [24]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray
arr1 = np.array(FIELDS)
print(arr1)
arr2 = np.array(DATATYPES)
print(arr2)

def load_data(filename, d = ','):
    data = np.genfromtxt(filename,delimiter = d, skip_header = 1,
                        usecols = np.arange(0,24),invalid_raise=False,
                        names = FIELDS, dtype = DATATYPES)
    return data

bs2017 = load_data('../Downloads/redsox_2017_hitting.txt')
bs2018 = load_data('../Downloads/redsox_2018_hitting.txt')

length_2017 = len(bs2017['SLG'])

avg_slg2017 = sum(bs2017['SLG']) / length_2017
print(f'\n Average SLG 2017: {avg_slg2017}')

length_2018 = len(bs2018['SLG'])
avg_slg2018 = sum(bs2018['SLG']) / length_2018
print(f'\n Average SLG 2018: {avg_slg2018}')

# I couldn't figure out how to use ndarray, but I wanted to at least take a shot at comparing the data
# the best way I knew how and this is what I was able to come up with

['Rk' 'Pos' 'Name' 'Age' 'G' 'PA' 'AB' 'R' 'H' '2B' '3B' 'HR' 'RBI' 'SB'
 'CS' 'BB' 'SO' 'BA' 'OBP' 'SLG' 'OPS' 'OPS+' 'TB' 'GDP' 'HBP' 'SH' 'SF'
 'IBB']
[['rk' 'i']
 ['pos' '|S25']
 ['name' '|S25']
 ['age' 'i']
 ['g' 'i']
 ['pa' 'i']
 ['ab' 'i']
 ['r' 'i']
 ['h' 'i']
 ['2b' 'i']
 ['3b' 'i']
 ['hr' 'i']
 ['rbi' 'i']
 ['sb' 'i']
 ['cs' 'i']
 ['bb' 'i']
 ['so' 'i']
 ['ba' 'f']
 ['obp' 'f']
 ['slg' 'f']
 ['ops' 'f']
 ['opsp' 'i']
 ['tb' 'i']
 ['gdp' 'i']
 ['hbp' 'i']
 ['sh' 'i']
 ['sf' 'i']
 ['ibb' 'i']]

 Average SLG 2017: 0.39334782374941785

 Average SLG 2018: 0.38750000335276125
